name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Go version inside container
        run: go version

      - name: Run tests inside container
        run: |
          go version
          go test -v ./...